#!/bin/bash

# This script will randomly go through the files of a directory, setting it
# up as the wallpaper at regular intervals
#
# NOTE: this script uses bash (not POSIX shell) for the RANDOM variable

if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
	echo "Usage:
	$0 <dir containing images>"
	exit 1
fi

# Edit below to control the images transition
export SWWW_TRANSITION_FPS=144
export SWWW_TRANSITION_STEP=2
export SWWW_TRANSITION_TYPE=random

# This controls (in seconds) when to switch to the next image
INTERVAL=90

while true; do
	find "$1" \
		| while read -r img; do
			echo "$((RANDOM % 1000)):$img"
		done \
		| sort -n | cut -d':' -f2- \
		| while read -r img; do
			TRANS=$(shuf -i 10-100 -n 1)
			TPOS1=$(printf "0.%03d" $(( RANDOM % 1000 )))
			TPOS2=$(printf "0.%03d" $(( RANDOM % 1000 )))
			#swww img "$img" --transition-type outer --transition-pos 0.854,0.977 --transition-step ${TRANS}
			swww img "$img" --transition-type outer --transition-pos ${TPOS1},${TPOS2} --transition-step ${TRANS}
			sleep $INTERVAL
		done
done
